### ISSUE TITLE
[HELP] how did you add this to hyperpipe

### ISSUE THREAD

**Issue by ghost** [httpjamesm/whatever.social-launchpad#20]
How did you add make "local/remove playlist"
![image](https://user-images.githubusercontent.com/118383308/202771526-94722a60-a53a-4529-9b83-bf4dca98e7b1.png)

**Comment by privacytime101** [comment]
> How did you add make "local/remove playlist"
> 
>

We didn't make Hyperpipe, check https://codeberg.org/Hyperpipe/Hyperpipe

**Comment by httpjamesm** [comment]
How is this at all related to Whatever’s launchpad? Closing this irrelevant issue.
